/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_content_delivery_bucket": "mypags-20241007234619-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "ap-northeast-2",
    "aws_content_delivery_url": "https://d25msum2rm2dt2.cloudfront.net"
};


export default awsmobile;
